---
- name: install packages on webserver
  hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: install httpd package
      package:
        name: "{{item}}"
        state: present
      with_items:
        - httpd
        - elinks
