---
- name: Playbook for tasks
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install multiple packages
      package:
        name: "{{item}}"
        state: removed
      with_items:
        - bind-utils
        - elinks
        - curl
        - gzip
          
          

