---
- name: clear servers
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: stop service
      service: name=httpd state=stopped enabled=no

    - name: remove httpd package
      yum: name=httpd  state=absent 

    - name: remove index.html
      file: path=/var/www/html/index.html  state=absent