---
- name: create a simple static website with apache
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: make sure apache is installed and latest version
      yum: name=httpd  state=latest
    
    - name: start and enable apache
      service: name=httpd  state=started enabled=yes

    - name: create an index file inside /var/www/html
      file: path=/var/www/html/index.html state=touch owner=root group=root 

    - name: Write a simple content for index file
      lineinfile: path=/var/www/html/index.html  line='Hello! This is my static index page'
      notify:
        - restart my apache
  handlers:
    - name: restart my apache
      service: name=httpd state=restarted




